# &def
# $expr
# i8,u8,i16,u16,i32,u32,i64,u64,f32,f64

# https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html
byte_order = "big-endian"
root_node = "ClassFile"
u1 = "&u8"
u2 = "&u16"
u4 = "&u32"

#ClassFile {
#    u4             magic;
#    u2             minor_version;
#    u2             major_version;
#    u2             constant_pool_count;
#    cp_info        constant_pool[constant_pool_count-1];
#    u2             access_flags;
#    u2             this_class;
#    u2             super_class;
#    u2             interfaces_count;
#    u2             interfaces[interfaces_count];
#    u2             fields_count;
#    field_info     fields[fields_count];
#    u2             methods_count;
#    method_info    methods[methods_count];
#    u2             attributes_count;
#    attribute_info attributes[attributes_count];
#}
[ClassFile]
magic = "&u4:0x%X"
minor_version = "&u2"
major_version = "&u2"
constant_pool_count = "&u2"
#constant_pool = "&cp_info[${constant_pool_count - 1}]"
#access_flags = "&u2"
#this_class = "&u2"
#super_class = "&u2"
#interfaces_count = "&u2"
#interfaces = "&u2[$interfaces_count]"
#fields_count = "&u2"
#fields = "&field_info[$fields_count]"
#methods_count = "&u2"
#methods = "&method_info[methods_count]"
#attributes_count = "&u2"
#attributes = "&attribute_info[$attributes_count]"

#cp_info {
#    u1 tag;
#    u1 info[];
#}

[cp_info]
tagged = true
tag_type = "&u1"
 1 = "&CONSTANT_Utf8"
 3 = "&CONSTANT_Integer"
 4 = "&CONSTANT_Float"
 5 = "&CONSTANT_Long"
 6 = "&CONSTANT_Double"
 7 = "&CONSTANT_Class"
 8 = "&CONSTANT_String"
 9 = "&CONSTANT_Fieldref"
10 = "&CONSTANT_Methodref"
11 = "&CONSTANT_InterfaceMethodref"
12 = "&CONSTANT_NameAndType"
15 = "&CONSTANT_MethodHandle"
16 = "&CONSTANT_MethodType"
17 = "&CONSTANT_Dynamic"
18 = "&CONSTANT_InvokeDynamic"
19 = "&CONSTANT_Module"
20 = "&CONSTANT_Package"

#CONSTANT_Utf8_info {
#    u1 tag;
#    u2 length;
#    u1 bytes[length];
#}
[CONSTANT_Utf8_info]
tag = "&u1"
length = "&u2"
bytes = "&u8[$length]"

#CONSTANT_Integer_info {
#    u1 tag;
#    u4 bytes;
#}
[CONSTANT_Integer_info]
tag = "&u1"
val = "&i32"

#CONSTANT_Float_info {
#    u1 tag;
#    u4 bytes;
#}
[CONSTANT_Float_info]
tag = "&u1"
val = "&f32"

#CONSTANT_Long_info {
#    u1 tag;
#    u4 high_bytes;
#    u4 low_bytes;
#}
[CONSTANT_Long_info]
tag = "&u1"
val = "&i64"

#CONSTANT_Double_info {
#    u1 tag;
#    u4 high_bytes;
#    u4 low_bytes;
#}
[CONSTANT_Double_info]
tag = "&u1"
val = "&f64"

[field_info]
[method_info]
[attribute_info]
