# &def
# $expr
# i32,u32,i64,u64,f32,f64

# https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html
byte_order = "big-endian"
root_node = "ClassFile"
u2 = "&u16"
u4 = "&u32"

#ClassFile {
#    u4             magic;
#    u2             minor_version;
#    u2             major_version;
#    u2             constant_pool_count;
#    cp_info        constant_pool[constant_pool_count-1];
#    u2             access_flags;
#    u2             this_class;
#    u2             super_class;
#    u2             interfaces_count;
#    u2             interfaces[interfaces_count];
#    u2             fields_count;
#    field_info     fields[fields_count];
#    u2             methods_count;
#    method_info    methods[methods_count];
#    u2             attributes_count;
#    attribute_info attributes[attributes_count];
#}
[ClassFile]
magic = "&u4"
minor_version = "&u2"
major_version = "&u2"
constant_pool_count = "&u2"
constant_pool = "&cp_info[${constant_pool_count - 1}]"
access_flags = "&u2"
this_class = "&u2"
super_class = "&u2"
interfaces_count = "&u2"
interfaces = "&u2[$interfaces_count]"
fields_count = "&u2"
fields = "&field_info[$fields_count]"
methods_count = "&u2"
methods = "&method_info[methods_count]"
attributes_count = "&u2"
attributes = "&attribute_info[$attributes_count]"

[cp_info]
[field_info]
[method_info]
[attribute_info]
